### ISSUE TITLE
Support flat-style style

### ISSUE THREAD

**Issue by ScanCaster** [rxu/thanks_for_posts#106]
Request for support of the flat-style style for the ext, please.

https://www.phpbb.com/customise/db/style/flat_style/

Default orange theme, would be my preference.

Thanks!

**Comment by rxu** [comment]
It works for me without any additional actions.

![image](https://user-images.githubusercontent.com/212322/80667275-f06d2b00-8ac8-11ea-9377-f4ac5d470820.png)

**Comment by t0rxe** [comment]
Just letting you know that this ticket is still open. If it's been resolved/fixed, you should close it :)
