### ISSUE TITLE
exclude stars in recent topics

### ISSUE THREAD

**Issue by avandenberghe** [rxu/thanks_for_posts#108]
hello, 

how would i have to go about to exclude stars to be shown in the recent topics pane ? 
Is there an event you subscribe to ?

best regards,
Andreas

**Comment by rxu** [comment]
Hi,

what recent topics pane do you mean?

**Comment by avandenberghe** [comment]
from my extension https://github.com/Sajaki/RecentTopics/issues/118

**Comment by rxu** [comment]
Oh.
This is it I guess https://github.com/rxu/thanks_for_posts/blob/develop-3.2.x/styles/prosilver/template/event/topiclist_row_append.html
Deleting lines 3-4 should do it.

**Comment by avandenberghe** [comment]
thanks!
