### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: The routing file "C:\xampp\htdocs\ext/gfksx/ThanksForPosts/config/routing.yml" contains unsupported keys for "gfksx_ThanksForPosts_thankslist_controller_user": "pattern". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition", "controller". in C:\xampp\htdocs\vendor\symfony\routing\Loader\YamlFileLoader.php on line 206

### ISSUE THREAD

**Issue by Arxero** [rxu/thanks_for_posts#109]
Hey I am not completely sure if this is the right place post it but this is what I got after updating my Phpbb 3.2.3 version forum to the current 3.3.1 I would be glad to know how this can be fixed and what is the problem with it, I am not good at PHP so excuse me if it lame.

![download (13)](https://user-images.githubusercontent.com/30701352/90694120-c8c0ef00-e280-11ea-941d-9606b5dbf40c.png)

**Comment by rxu** [comment]
Extension version you're using seems to be way too old.
You need to upgrade to the latest version 2.0.7, see https://www.phpbb.com/customise/db/extension/thanks_for_posts_2/faq/2626

**Comment by Arxero** [comment]
Thank you I have updated the way they say here > 
https://www.phpbb.com/support/docs/en/3.3/ug/upgradeguide/upgrade32/

and followed your instructions and all is working fine now, thank you.
