### ISSUE TITLE
Warning: 'composer.json' has different a directory string

### ISSUE THREAD

**Issue by t0rxe** [rxu/thanks_for_posts#110]
Just a small warning, but the file 'composer.json' has this line of code: `"name": "gfksx/thanksforposts",`
In other versions it has leading uppercase strings: `"name": "gfksx/ThanksForPosts",`
This results in the extension not being found in phpBB because of a mismatch.

**Comment by rxu** [comment]
What version are you referring to?
There're different versions with 2 different naming. See https://www.phpbb.com/customise/db/extension/thanks_for_posts_2/faq/2626

**Comment by t0rxe** [comment]
Ah, I must have tried the other version and that's thrown me off. Thanks for clearing that up :)

**Comment by rxu** [comment]
You're welcome.
