### ISSUE TITLE
Question for icons

### ISSUE THREAD

**Issue by TakeOwer** [rxu/thanks_for_posts#122]
Hi,
I wanted to know if it was possible to replace the thank you icon with this icon of mine.
![thankposts](https://github.com/rxu/thanks_for_posts/assets/174133028/0cdc8bae-0fe1-4330-836c-b9a4c5f19968)

to make the icons homogeneous with the existing ones
![icons](https://github.com/rxu/thanks_for_posts/assets/174133028/04d48faa-d1db-4418-8d94-967e2b8734e8)

Great extension 👍  
Thanks
Best Regards

Salvo

**Comment by rxu** [comment]
It's here https://github.com/rxu/thanks_for_posts/blob/d70c68c6f57bc49a787eb23ef5a8a7f9999cec00/styles/prosilver/template/event/viewtopic_body_post_buttons_after.html#L6

Bit I guess you could actually create a folder named after your style in the `ext/gfksx/thanksforposts/styles`, copy the content of the `ext/gfksx/thanksforposts/styles/prosilver` there and than change that line in according to your style just to keep prosilver untouched.

**Comment by TakeOwer** [comment]
Hi,
thanks for the prompt reply. I tried to create my "forumus" style folder and copied the "prosilver" style files there. Unfortunately I don't know how to add the 2 images, since they are not "fa-" icons.
I could use some further help.

Thanks in advance
Salvo

This is the code, but it does not work!
`<i class='icon {% if postrow.THANKED %}'<img src="images/removethanks.gif" />{% else %}<img src="images/thankposts.gif" />{% endif %} aria-hidden="true"></i><span class="sr-only">{{ postrow.THANK_ALT_SHORT }}</span>`

**Comment by rxu** [comment]
What phpBB style are you using? ~Download or demo link would be helpful.~

EDIT: I see now it's a paid ForumUS style. Can't actually test it, but that would look just like
```html
			<a id='lnk_thanks_post{{ postrow.POST_ID }}' {% if S_AJAX_ENABLED %}data-ajax="handle_thanks" {% endif %}href="{{ postrow.THANKS_LINK }}" title="{{ postrow.THANK_ALT }}{{ postrow.POST_AUTHOR }}"  class="button icon-button">
				<img src="./path_to_the_icon_file">
			</a>
```

**Comment by TakeOwer** [comment]
Hi,
thank you for your support. I tried your code as follows

`<a id='lnk_thanks_post{{ postrow.POST_ID }}' {% if S_AJAX_ENABLED %}data-ajax="handle_thanks" {% endif %}href="{{ postrow.THANKS_LINK }}" title="{{ postrow.THANK_ALT }}{{ postrow.POST_AUTHOR }}"  class="button icon-button">
			{% if postrow.THANKED %}
				<img src="{T_THEME_PATH}/images/removethanks.gif" aria-hidden="true"><span class="sr-only">{{ postrow.THANK_ALT_SHORT }}</span>
			{% else %}
				<img src="{T_THEME_PATH}/images/thankposts.gif" aria-hidden="true"><span class="sr-only">{{ postrow.THANK_ALT_SHORT }}</span>
			{% endif %}
		</a>`

In fact the image is now visible, but unfortunately it is not aligned with the others. There appears to be another image below!
![thanks_image_forumus](https://github.com/rxu/thanks_for_posts/assets/174133028/9c57e5cc-a104-4530-ae01-9d1e44c1988b)

Some idea? Do I need to modify any other files?
Best Regards
Salvo

**Comment by TakeOwer** [comment]
Hi,
thank you for your support. I tried your code as follows

`<a id='lnk_thanks_post{{ postrow.POST_ID }}' {% if S_AJAX_ENABLED %}data-ajax="handle_thanks" {% endif %}href="{{ postrow.THANKS_LINK }}" title="{{ postrow.THANK_ALT }}{{ postrow.POST_AUTHOR }}">
			{% if postrow.THANKED %}
				&nbsp;&nbsp;<img src="{T_THEME_PATH}/images/removethanks.gif" aria-hidden="true"><span class="sr-only">{{ postrow.THANK_ALT_SHORT }}</span>
			{% else %}
				&nbsp;&nbsp;<img src="{T_THEME_PATH}/images/thankposts.gif" aria-hidden="true"><span class="sr-only">{{ postrow.THANK_ALT_SHORT }}</span>
			{% endif %}
		</a>`

![thanks_iamge_forumus](https://github.com/rxu/thanks_for_posts/assets/174133028/35083adc-9147-4251-bf7b-bcbed2554cde)

Thus the problem is solved now 😀
Thank you very much

Salvo
