### ISSUE TITLE
Issue Thanklist pagination - URL problem duplicate

### ISSUE THREAD

**Issue by vwdeiu** [rxu/thanks_for_posts#123]
Hello.

There's an issue with the thanklist / toplist pagination!

When I try to go on page 2,3,4..etc, the url redirects me to 
`https://metin2.forum/app.php/thankslist/givens/2/app.php/thankslist/givens/2/true?start=10`

instead of:
`https://metin2.forum/app.php/thankslist/givens/2/true?start=10`

How to fix this?

On toplist the url redirects me to
`https://metin2.forum/app.php/app.php/thankslist?start=25`

instead of the correct url:
`https://metin2.forum/app.php/thankslist?start=25`

**Comment by vwdeiu** [comment]
@rxu

**Comment by rxu** [comment]
Couldn't reproduce the issue. What extension version?

**Comment by vwdeiu** [comment]
> Couldn't reproduce the issue. What extension version?

v2.1.0

phpbb 3.3.13

website link to see the issue: https://metin2.forum/app.php/thankslist/givens/2/true **(try to change the page)**

**Comment by rxu** [comment]
Is the issue relevant if you switch to prosilver style?

**Comment by vwdeiu** [comment]
> Is the issue relevant if you switch to prosilver style?

Yes, the issue is present on prosilver too. I found another forum that has this problem too.. so its not an isolated case.

Here you have attached the extension I use:

[thanksforposts.zip](https://github.com/user-attachments/files/17787611/thanksforposts.zip)

**Comment by vwdeiu** [comment]
@rxu I can't figure out why it does that..

**Comment by rxu** [comment]
As far as I can see, there's some kind of 'SEO' extension installed on the board. That is likely the cause, you can make it sure disabling the SEO extension temporarily.

**Comment by vwdeiu** [comment]
> As far as I can see, there's some kind of 'SEO' extension installed on the board. That is likely the cause, you can make it sure disabling the SEO extension temporarily.

I cant disable it unfortunately.. it would kill my seo score.

Is it anything I can do for the link to work correctly?

`https://metin2.forum/app.php/thankslist?start=25
`
instead of

`https://metin2.forum/app.php/app.php/thankslist?start=25`

**Comment by rxu** [comment]
> I cant disable it unfortunately.. it would kill my seo score.

I meant disabling for a minute, just to make sure it's not this but SEO extension issue.

> Is it anything I can do for the link to work correctly?

Can't tell as it completely depends on the SEO extension internals (f.e. URL rewrite templates and rules).

**Comment by vwdeiu** [comment]
**I managed to fix this.** @rxu 

The fix is from the SEO Ultimate Module extension.

Go to event>**listener.php** and search for:

```
	public function core_pagination_generate_page_link($event)
	{
		static $paginated = [], $find = ['{SN}', '{SV}'];

		$base_url = $event['base_url'];
		$on_page = $event['on_page'];
		$start_name = $event['start_name'];
		$per_page = $event['per_page']; 
```

Add below:

```
    if (strpos($base_url, '/thankslist/') !== false) {
        $event['base_url'] = $base_url; 
        return;
    }
```

**Comment by rxu** [comment]
Glad you've sorted this out, and thanks for posting back the solution.
