### ISSUE TITLE
thanks post not working when phpbb-seo is active

### ISSUE THREAD

**Issue by Persian-phpBB** [rxu/thanks_for_posts#15]
Hello

thanks post not working when phpbb-seo is active. the url of thanks is change:
http://www.php-bb.ir/forum/post1746.html?rthanks=1746&to_id=635&from_id=2

phpbb-seo:
https://github.com/phpBBSEO/usu

**Comment by CristiOprea** [comment]
and I have the same error! Please help meeeee!

**Comment by Leinad4Mind** [comment]
Same error here.

"Any errors? Do you have QSA parameter applied for rewrite rules?" Yes I've QSA parameter.

**Comment by rxu** [comment]
Looks like USU related issue https://github.com/rxu/thanks_for_posts/issues/27
