### ISSUE TITLE
subsilver2

### ISSUE THREAD

**Issue by miouser** [rxu/thanks_for_posts#25]
а когда можно будет ожидать поддержку стиля subsilver2?

**Comment by rxu** [comment]
Когда будет свободное время.

**Comment by miouser** [comment]
@rxu
такой ответ, радует. всяко лучше чем "пока кто то другой сделает" ;)

спасибо за труд!!!

**Comment by Galixte** [comment]
Hi,

In viewprofile i have two error messages:

```
Has thanked: [phpBB Debug] PHP Warning: in file [ROOT]/phpbb/user.php on line 505: sprintf(): Too few arguments

Clear Thanks List Been thanked: 4 times [phpBB Debug] PHP Warning: in file [ROOT]/phpbb/user.php on line 505: sprintf(): Too few arguments
```

Is there the same problem ?

**Comment by rxu** [comment]
Thanks for the bugreport.
Subsilver2 support has been added via b14ea302e213f05d6d1fa2f28482049c0bdb648b.
The bug has been fixed via 8487ef59ab0ebdbbbd9af41b82ce85edfa9be441.
