### ISSUE TITLE
Seo URL vs Thanks for posts error

### ISSUE THREAD

**Issue by CristiOprea** [rxu/thanks_for_posts#27]
Hi, I think you encountered and how SEO overlap problem with the phpBB 3.0.x. thanks for posts I have the same problem and I to 3.1.x and fail to do.
What is the problem this?
If it remains activated only posts thanks for extension works perfectly, can the crowd at any point. But if I turn and seo url, I give the "thanks" redirects me back to the subject and does not validate contentment. Please help me quickly. Thank you.
Link Extensions Seo URL: github. com/phpBBSEO/usu
Link Extensions Thanks for posts: github. com/rxu/thanks_for_posts

**Comment by omertelli** [comment]
And if user try to remove thanks ,they get error with github. com/phpBBSEO/usu

**Comment by Galixte** [comment]
phpbbSEO is not maintened since november 2014…

**Comment by wcz-txp** [comment]
Has someone found a solution?

**Comment by wcz-txp** [comment]
a workaround can be to modify `/ext/phpbbseo/usu/event/listener.php` like once the mod:
`290a291,294
> // Thanks for Posts extension
>     $to_id = request_var('to_id', 0);
>     $thanks = request_var('thanks', 0);
>     $rthanks = request_var('rthanks', 0);
291a296,297
> //				        if ( ($rthanks || $thanks) || ($post_id && !$view && !$phpbb_seo->set_do_redir_post()))
> // Thanks for Posts extension
295a302,306
> // Thanks for Posts extension
> 							'rthanks' => array('val' => $rthanks, 'keep' => $rthanks),
> 							'to_id' => array('val' => $to_id, 'keep' => $to_id),
> 							'thanks' => array('val' => $thanks, 'keep' => $thanks),
> // Thanks for Posts extension
341c352,360
< 					$this->core->zero_dupe();
---
> // Thanks for Posts extension
> //					$this->core->zero_dupe();
> 					if (!$to_id && !$thanks && !$rthanks) {
> 						$this->core->zero_dupe();
> 				        }
> // Thanks for Posts extension
`

**Comment by wcz-txp** [comment]
Following the [old solution for phpbb 3.0.x](http://www.phpbb-seo.com/en/advanced-seo-url/article4908.html) these edits helped me out with phpbb 3.1.8 and Thanks for Posts from 16.01.2016 and usu from 9.08.2015:
In `/ext/phpbbseo/usu/event/listener.php` look for

`if ($post_id && !$view && !$this->core->set_do_redir_post())`

**replace with**

```
// Thanks for Posts extension
 					$to_id = request_var('to_id', 0);
 					$thanks = request_var('thanks', 0);
 					$rthanks = request_var('rthanks', 0);
//					if ($post_id && !$view && !$this->core->set_do_redir_post())
 				        if (($rthanks || $thanks || $post_id)  && !$view && $this->core->set_do_redir_post())
// Thanks for Posts extension
```

Then look for 
`'hilit'	=> array('val' => (($highlight_match) ? $highlight : ''), 'keep' => !empty($highlight_match)),`

And **add after**

```
// Thanks for Posts extension
 							'rthanks' => array('val' => $rthanks, 'keep' => $rthanks),
 							'to_id' => array('val' => $to_id, 'keep' => $to_id),
 							'thanks' => array('val' => $thanks, 'keep' => $thanks),
// Thanks for Posts extension
```

then look for `$this->core->zero_dupe();`

and **replace with**

```  
// Thanks for Posts extension
//					$this->core->zero_dupe();
					if (!$to_id && !$thanks && !$rthanks) {
  						$this->core->zero_dupe();
  				        }
// Thanks for Posts extension
```

Clean your cache and then it should work. 
Maybe a more talented one prepares a commit for the [repository](https://github.com/phpBBSEO/usu).

**Comment by rxu** [comment]
Thanks. The problem is that USU repo is abandoned, the last commit is from August 2015

**Comment by wcz-txp** [comment]
I know, but as it is, it's working for me, ok obviously with some obstacles :-).

**Comment by meis2m** [comment]
it is not working yet...

extension is here:
https://github.com/phpbb-seo/usu

**Comment by rxu** [comment]
No plans for support SEO ext, sorry.
Feel free to send PR to this repo anyway.
