### ISSUE TITLE
 Posts toplist & Thanks list URLs

### ISSUE THREAD

**Issue by Galixte** [rxu/thanks_for_posts#28]
Hi,

i have a new bug since your last modifications, if i go in "Quick links" then i click on:
- Posts toplist => the page is: http://mydomain.tld/app.php/thankslist instead of http://mydomain.tld/app.php/toplist
- Thanks list => the page is: http://mydomain.tld/app.php/thankslist GOOD PAGE !

If i activate "Enable URL Rewriting" in Server settings:
- Posts toplist => the page is: http://mydomain.tld/thankslist instead of http://mydomain.tld/toplist
- Thanks list => the page is: http://mydomain.tld/thankslist GOOD PAGE !

**Comment by rxu** [comment]
Thanks a lot for reporting, fixed.

**Comment by Galixte** [comment]
It is a pleasure
