### ISSUE TITLE
Compatiblity with User Topic Count extension

### ISSUE THREAD

**Issue by Galixte** [rxu/thanks_for_posts#33]
Hi,

could you take a look ? https://github.com/marttiphpbb/phpbb-ext-usertopiccount/issues/3

**Comment by Galixte** [comment]
I propose this PR to fix it: https://github.com/rxu/thanks_for_posts/pull/38

**Comment by rxu** [comment]
The issue should be fixed now. Closing.

**Comment by Galixte** [comment]
Thanks you. ;)
