### ISSUE TITLE
Thanks button doesn't show

### ISSUE THREAD

**Issue by Electrix** [rxu/thanks_for_posts#35]
Small bug in prosilver: If you have a forum, to which user cannot reply and/or report posts (= no control panel buttons), the "thanks" button will not show up, even if the user has "can thank to post" permisson.

I'm aware, that this issue cannot be fixed without change in phpBB's code, just wanted you to know.

**Comment by rxu** [comment]
It shouldn't depend on any other permission than ```f_thanks```. Also, subsilver2 has the same conditions to display the button as prosilver. Are you sure this is the extension issue?

**Comment by Electrix** [comment]
Well, it's hard to tell. Problem is in this file:

_/styles/prosilver/template/viewtopic_body.html_

There is this condition, that determines, if phpBB should show the row with buttons like "quote", "edit" etc.

`<!-- IF postrow.U_EDIT or postrow.U_DELETE or postrow.U_REPORT or postrow.U_WARN or postrow.U_INFO or postrow.U_QUOTE -->`

at the end of this row, there is an event that your extension uses

`<!-- EVENT viewtopic_body_post_buttons_after -->`

But if a user has no rights for edit/delete/report/info/warn/quote, but he HAS rights to thank, the thanks button will still not show up (because whole row is hidden).

P.S.: I internally fixed this by changing the condition to
`<!-- IF postrow.U_EDIT or postrow.U_DELETE or postrow.U_REPORT or postrow.U_WARN or postrow.U_INFO or postrow.U_QUOTE or S_FORUM_THANKS -->`

My apologize, if this is a wrong place to adress the issue, I just though you would know better.

**Comment by rxu** [comment]
Hmm. Indeed, this is just about the ```EVENT viewtopic_body_post_buttons_after``` placement. Can't see the good way to correct it for now.

**Comment by rxu** [comment]
New prosilver template event was added to phpBB 3.1.5: ```viewtopic_body_post_buttons_list_after```, which allowed to fix the issue. Thanks for reporting.

**Comment by Galixte** [comment]
Hi,

could you confirm that phpBB 3.1.4 doesn’t display the Trnaks button on viewtopic ? If yes, maybe you should add the necessary information about this extension that only works on phpBB 3.1.5.

**Comment by rxu** [comment]
@Galixte It does display the button. The only case is when user doesn't have permissions to quote, edit, delete, report post and warn for post alltogether, which is very rare.

**Comment by Galixte** [comment]
@rxu, if i revert your last change here: https://github.com/rxu/thanks_for_posts/commit/99b0e7af26a93944b3f85a38ce7a955759b7b54f the button is displayed, if i use your last change it’s not displayed.

**Comment by rxu** [comment]
Ah, now I see what do you mean. Current development state is not compatible with 3.1.4 since the latter doesn't have ```viewtopic_body_post_buttons_list_after``` template event.
But changing composer.json won't actually stop the ext from installing on earlier versions, it requires some additions to the ```ext.php``` file.

**Comment by Galixte** [comment]
Thanks for confirmation. I will update to 3.1.5.

**Comment by Galixte** [comment]
Hi @rxu,

thanks for revert with your last commit here: https://github.com/rxu/thanks_for_posts/commit/8aa884eb60c8350c2a9a622e490017ab8dd1a7dc.

But now the issue presents here is opened again, no ?
