### ISSUE TITLE
Thanks for posts and Topic solved extension on viewtopic

### ISSUE THREAD

**Issue by Galixte** [rxu/thanks_for_posts#41]
Hi @rxu,

in response to this Thread: https://github.com/rxu/thanks_for_posts/issues/35

on phpBB 3.1.5, with this extension: https://github.com/tierra/topicsolved there is a bug on viewtopic with post-related buttons. But without this additional extension , there is also a bug in viewtopic (see point n°2).

The facts are simple:
- point n°1: if no extension is activated, the last button is the QUOTE button, OK
- point n°2: if Thanks for posts extension is activated, the last button is the THANKS button but the QUOTE button is not displayed (is it behind the thanks button?), NOT OK
- point n°3: if Topic solved extension is activated, the last button is the TOPIC SOLVED button and no previous buttons are missing, OK
- point n°4: if Thanks for posts and Topic solved extensions are activated, the last button is the THANKS button but the TOPIC SOLVED button is not displayed (is it behind the thanks button ?), NOT OK.

Actually, to solve this problem, i have to revert your last commit about the viewtopic, here:https://github.com/rxu/thanks_for_posts/commit/99b0e7af26a93944b3f85a38ce7a955759b7b54f.

**Comment by rxu** [comment]
Thanks, I'm aware of this problem. That's a css layout issue so the fix will take some time.

**Comment by tierra** [comment]
I would recommend sticking with the `viewtopic_body_post_buttons_after` template event, and using the appropriate `<li>` markup and styles consistent with the existing Prosilver post buttons. The extra `<ul>` likely makes this much more difficult to maintain compatibility with Prosilver, and other Prosilver-based styles. The CSS layout provided by Prosilver should be easier to reuse that way too.

**Comment by rxu** [comment]
@tierra the problem with the old solution is #35 issue.

**Comment by Galixte** [comment]
Fixed since this: https://github.com/rxu/thanks_for_posts/issues/35#issuecomment-128541047.
