### ISSUE TITLE
Thank icon and mobile devices

### ISSUE THREAD

**Issue by MaFeSa** [rxu/thanks_for_posts#42]
There is a problem with mobile devices, tested with phpBB 3.1.5
![icon](https://cloud.githubusercontent.com/assets/1554203/8929997/101c8490-352a-11e5-9180-17e5cce3e7d2.png)

Many thanks

**Comment by Galixte** [comment]
Hi @MaFeSa,

it’s fixed since this commit: https://github.com/rxu/thanks_for_posts/commit/8aa884eb60c8350c2a9a622e490017ab8dd1a7dc.

**Comment by MaFeSa** [comment]
Hi, sorry but this problem is still present...
With normal user all is fine but with administrator or moderator I can't view post options.
Thanks

**Comment by mastum** [comment]
Fixed with phpBB 3.2.0
