### ISSUE TITLE
Problems with notification after disabling extension

### ISSUE THREAD

**Issue by ccondrup** [rxu/thanks_for_posts#47]
This extension was not compatible with the custom theme we use (Flatboots), so I tried to disable the extension. Now a couple of users (probably only the ones with new notifications) are generating this in the error_log:

	PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'The service definition "gfksx.thanksforposts.notification.type.thanks" does not exist.' in vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:871
	Stack trace:
	#0 vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php(478): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('gfksx.thanksfor...')
	#1 phpbb/notification/manager.php(905): Symfony\Component\DependencyInjection\ContainerBuilder->get('gfksx.thanksfor...')
	#2 phpbb/notification/manager.php(885): phpbb\notification\manager->load_object('gfksx.thanksfor...')
	#3 phpbb/notification/manager.php(228): phpbb\notification\manager->get_i in vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 871

I have: Disabled extension in ACP. Deactivated extension in db. Deleted extension files.
What more needs to be done to "clean up"? Thanks.

**Comment by Galixte** [comment]
You missed to delete data after have disabled the extension.

“Deactivated extension in db.” what does it mean ? By PhpMyAdmin ? Who asked you to do that ? Delete data after disabled is the good way.

**Comment by ccondrup** [comment]
Thanks, I understand I have been looking at the problem from the wrong perspective. I got a theme error even after disabling the extension and I wanted to keep the data so it could be re-enabled when the theme was fixed, that's why the data was not deleted. Works now, thanks for a really rapid response!
