### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by bagda391** [rxu/thanks_for_posts#49]
Where is the installation guide? 
Thanks.

**Comment by Galixte** [comment]
Hi @bagda391,

it’s common for all extensions: https://www.phpbb.com/extensions/installing/, except that on GitHub the downloaded archive are not ready to install.

You have to rename correctly the folder names, like logic explained in guide above.

To help you, edit the ```composer.json``` file in line 2, to know the correct names of the two main folders.

**Comment by rxu** [comment]
See https://www.phpbb.com/community/viewtopic.php?f=456&t=2259046
