### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bagda391** [rxu/thanks_for_posts#50]
Hello!

I want to implement some custom features to the code. I need some help in locating where I can change the code for all these:
To Do list:
1. Convert “thanks” to upvote or other term for topic
2. Create new upvote/remove vote buttons
3. Create sortable column for topic upvote count
4. “List of thanks” provides a listing of users who have been thanked rather than a listing of topics/posts that have been thanked. Topic/Post upvote page should be created.
5. Change presentation of upvotes in a post

**Comment by Galixte** [comment]
In other way you want a new extension :)

**Comment by bagda391** [comment]
Where can I find all the strings such as "thanked the author" etc ? That's one of the questions

**Comment by bagda391** [comment]
Solved most of them. I want to know how I can sort based on number of thanks like here: https://gyazo.com/29564352bed73122635f218f6cd859d6

**Comment by rxu** [comment]
This is not bugs report, so closing the ticket.
