### ISSUE TITLE
Sortable dropdown menu for # of upvotes

### ISSUE THREAD

**Issue by bagda391** [rxu/thanks_for_posts#62]
Is this implemented? If not how can I implement it?

**Comment by rxu** [comment]
Elaborate please.

**Comment by bagda391** [comment]
https://gyazo.com/b995233c936fb6737d3e099c60c26be7 sort by from here but based on number of likes

**Comment by rxu** [comment]
You mean sorting topics ina forum?

**Comment by bagda391** [comment]
Yes. By number of upvotes. How can I implement this if not already there?

**Comment by rxu** [comment]
I think that is not that trivial task and would require editing core phpBB files, as there's no suitable event to modify topics sorting.
Thus this can't be done in extension for now.
