### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bagda391** [rxu/thanks_for_posts#65]
Where can I find the size of the thanks button? (not the image itself, just the button)

Thanks.

**Comment by rxu** [comment]
It's handled here https://github.com/rxu/thanks_for_posts/blob/master/styles/prosilver/theme/thanks.css#L65-L79
Next time please don't use issue tracker to ask questions. There's the extension development topic for that: https://www.phpbb.com/community/viewtopic.php?f=456&t=2259046

Thanks.
