### ISSUE TITLE
Only ACP settings are displaying

### ISSUE THREAD

**Issue by byjuchalad** [rxu/thanks_for_posts#67]
Only ACP settings are displaying in prosilver.  No other Thanks for post screens are coming either view topic or post reply or new post.  The index page is also showing nothing related to thanks for post.  phbbb version is 3.1.8

**Comment by rxu** [comment]
Works fine for me on phpBB 3.1.8. Please provide more details for your issue. What branch did you download? ```develop-3.2.x``` is for phpBB 3.2 and is not compatible with phpBB 3.1.

**Comment by byjuchalad** [comment]
Thank for your suggestion.  Now it is working.

On Wed, Mar 30, 2016 at 10:28 PM, rxu <notifications@github.com> wrote:

> Works fine for me on phpBB 3.1.8. Please provide more details for your
> issue. What branch did you download? develop-3.2.x is for phpBB 3.2 and
> is not compatible with phpBB 3.1.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rxu/thanks_for_posts/issues/67#issuecomment-203526496>
>



-- 
"What is your Choice? Violence or Active Nonviolence. Take a Stand now".
Say NO to VIOLENCE, YES to LIFE. Support Peace and active nonviolence.
www.humanistforum.in
www.silo.net
www.geocities.ws/humanist
