### ISSUE TITLE
Invalid thank

### ISSUE THREAD

**Issue by Mickroz** [rxu/thanks_for_posts#72]
on my 3.2.0-RC1 board, when pressing the thanks button, i get a HTTP ERROR 500 page, after reloading i get Invalid thank return to post, after returning, the post is thanked.

**Comment by rxu** [comment]
What ext branch do you install from/

**Comment by Mickroz** [comment]
master, i think i downloaded it from ext dev forum, i see the 3.2 branch now, will try that one.

**Comment by Mickroz** [comment]
yes dev version fixes it.
