### ISSUE TITLE
very serious security issue

### ISSUE THREAD

**Issue by ser** [rxu/thanks_for_posts#73]
Some user-hacker just thanked 99 times for the same post, it's clearly some XSS or something...

![99-thanks](https://cloud.githubusercontent.com/assets/231537/20782192/12c1ed5a-b7bc-11e6-9239-b2c2026c04c3.jpg)

**Comment by Galixte** [comment]
Hi @rxu,

could you take a look, please ?

**Comment by ser** [comment]
maybe it would be sufficient to check if a particular user has not thanked for a particular post, before storing data in the sql server? It should not be too heavy, even with phpbb sql cache switched off. We should not use cache, as we can see on the image above, the script tool attacks the server in very short timescale.

**Comment by rxu** [comment]
What does this table mean?
Also, this has nothing to do with XSS and security.

**Comment by ser** [comment]
The table is _phpbb_thanks_ of course. It might be that it is much simpler than XSS, probably there is no control over how many times you can thank. I speculated. But of course it has to security, as you can make as many thanks as you want, demolishing the whole idea.

**Comment by rxu** [comment]
As far as I can see, ```user_id``` (the id of the user who thanked, the 3rd column in the table) is different for every 'thank'. How is that possible?
So it looks like registering new user rapidly and pushing thanks button.

**Comment by ser** [comment]
You're correct, I didn't notice that. Problem may be much more serious. It's rather not possible to register a new user so rapidly - captcha etc. - so it might be some XSS, then.

**Comment by rxu** [comment]
Then the problem is that some bot has broke through your board spambot countermeasures.
So the extension is not to blame in this case 😃

**Comment by ser** [comment]
No, there was no 99 users registered. It was done from one or max few users.

**Comment by rxu** [comment]
User id is ascending for every 'thank' as far as I can see.

**Comment by ser** [comment]
And when you had a look into a post, there was one user displayed who thanks - and there were 99 thanks. The same was on the user profile. Something is definitely wrong.

**Comment by rxu** [comment]
That sounds like registered username is the same for every user id.

**Comment by ser** [comment]
Hmm, how is it possible?

**Comment by rxu** [comment]
No idea. Could you attach the screenshot of the post with 99 thanks record below?

**Comment by ser** [comment]
The problem is that I was desperate to clean it up ASAP, so at the moment I'm not able to make a sophisticated diagnosis :( But as far as I know the users, it might happen in future...

**Comment by ser** [comment]
And, I think (additionally, from my emergency session) that if you delete a user, the module should delete thanks of that user. And now it does not.

**Comment by rxu** [comment]
Again, as that's not only 1 user but a number of, deleting 1 user is not enough as only 1 thank for the post will be deleted in that case.

**Comment by ser** [comment]
You know, please simulate that table locally and you will see that it's not a normal "thank" by multiple users. It was visible like one big 99 thank, on the profile and in the post. But unfortunately I'm not able to document it, as I deleted the data already directly in our SQL server. 

If the case is not clear enough, I will provide raw SQL dump next time when it happens.

**Comment by rxu** [comment]
Closing as this is not the extension issue.
