### ISSUE TITLE
phpBB 3.2.1 - Toplist page - Rating topics area - Topic icons don’t appear correctly

### ISSUE THREAD

**Issue by Galixte** [rxu/thanks_for_posts#87]
Hi @rxu,

on phpBB 3.2.1, on the toplist page, in “RATING TOPICS” table, the Topic icons don’t appear correctly

![thanks_for_post_-_thanks_toplist_-_rating_topics_li](https://user-images.githubusercontent.com/7478287/28501381-2d7eaa8e-6fdb-11e7-9ae9-baee275c186f.jpg)

**Comment by rxu** [comment]
Did you try Ctrl+F5 on this page in your browser?

**Comment by Galixte** [comment]
yes

**Comment by Galixte** [comment]
In those lines: 
- https://github.com/rxu/thanks_for_posts/blob/develop-3.2.x/styles/prosilver/template/toplist_body.html#L63
- https://github.com/rxu/thanks_for_posts/blob/develop-3.2.x/styles/prosilver/template/toplist_body.html#L96

by adding those CSS rules fixes the problem: ```display: table-cell; background-size: 32px;```.

**Comment by maras26** [comment]
Hi, where did you add to fix it ?

**Comment by rxu** [comment]
The toplist markup is planned to be refactored as per the current prosilver code.

**Comment by rxu** [comment]
Please try the latest code, it should be fixed.

**Comment by Galixte** [comment]
Ok, I will, thanks!

**Comment by Galixte** [comment]
Ok, fixed, thanks!
