### ISSUE TITLE
Database updates after renaming ThanksForPosts to thanksforposts

### ISSUE THREAD

**Issue by wcz-txp** [rxu/thanks_for_posts#96]
Hello,

I upgrade my board from an older version 3.1.10 to 3.2.2 and with this also thanksforposts. Everything is working now, but I had to manually rename all occurrences of gfksx/ThanksForPosts to gfksx/thanksforposts in the database for example the module names. Before I ran in errors like this:

` Uncaught Twig_Error_Loader: There are no registered paths for namespace "gfksx_thanksforposts" in "@gfksx_ThanksForPosts/event/overall_header_head_append.html" at line 1. in /var/www/forum/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:209
`

**Comment by rxu** [comment]
Please read upgrade instructions here https://www.phpbb.com/community/viewtopic.php?p=14911651#p14911651

Thanks.
